# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sudo
version:      0.32
version_from: lib/Sudo.pm
installdirs:  site
requires:
    Class::Accessor:               0.19
    IPC::Run:                      0.79
    Term::ReadPassword:            0.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
